### ISSUE TITLE
Open3.capture3({ENV_NAME: bar}, cmd) を検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#10]
何が悪いかと言うと、`Open3.capture3`の最初の引数に渡されるHashは環境変数になるが、そのkeyはStringでなくてはいけない(Symbolはダメ)。

これを実行するとTypeErrorが出るけど、

```
/usr/lib/ruby/2.4.0/open3.rb:199:in `spawn': no implicit conversion of Symbol into String (TypeError)
	from /usr/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /usr/lib/ruby/2.4.0/open3.rb:258:in `capture3'
	from /tmp/tmp.TX9kZKubu5/test.rb:3:in `<main>'
```

みたいなエラーメッセージで若干分かりづらいので、RuboCopで検出したい。
エラーメッセージから分かる通り、spawnとか他のcaptureXも検出したい。

実装はそこまで難しくないと思う。
ただ、「実行したら必ずエラーが出るのにCopにする必要があるの？」といわれそうな気はする。
私は「このコードをテストで実行してない時でも、Copになっていれば気がつけて便利」と思っているので、追加するべきだと思っています。

**Comment by pocke** [comment]
`Style/StringHashKeys` が Open3.capture3 では警告を出さないようにする変更も欲しい。
